### ISSUE TITLE
`wback` Exception Handling 

### ISSUE THREAD

**Issue by poorna2152** [poorna2152/nballerina#12]
[WebAssembly provides](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md) `try`, `catch`, `catchall`, `throw`, `rethrow` and `delegate` instructions for handling exceptions. However the exceptions which can be handled by the `catch` and `catchall` blocks are the exceptions which are explicitly thrown using the `throw` instruction.
In the following program if the second parameter is 0 it is expected to throw a division by zero error. But this error is not caught by the `catchall` block. It is caught by the runtime.
```
(module
  (type $i64_=>_none (func (param i64)))
  (type $i64_i64_=>_none (func (param i64 i64)))
  (import "console" "log" (func $println (param i64)))
  (export "testFunc" (func $testFunc))
    (func $testFunc (param $0 i64) (param $1 i64) (local $2 i64)
      (try
        (do
          (local.set $2
            (i64.div_s
              (local.get $0)
              (local.get $1)))
          (call $println
            (local.get $2)))
        (catch_all
          (call $println
            (i64.const -1))))))
```
Following works because we are explicitly throwing the error when second parameter is zero.
```
(module
  (type $i64_=>_none (func (param i64)))
  (type $i64_i64_=>_none (func (param i64 i64)))
  (import "console" "log" (func $println (param i64)))
  (tag $a-tag)
  (export "testFunc" (func $testFunc))
  (func $testFunc (param $0 i64) (param $1 i64)
    (try
      (do
        (if
          (i64.eq
            (local.get $1)
            (i64.const 0))
          (throw $a-tag)
          (call $println
            (i64.div_s
            (local.get $0)
            (local.get $1)))))
      (catch $a-tag
        (call $println
          (i64.const -1))))))
```

**Comment by poorna2152** [comment]
Exceptions can be handled using the `try catch` in the [JS file](https://github.com/poorna2152/nballerina/blob/wback_subset01_main/runtime/main.js#L16).
Considering the [div3-p.bal](https://github.com/poorna2152/nballerina/blob/wback_subset01_main/compiler/testSuite/01-int/div3-p.bal).
Expected output is,
```
panic: divide by zero
div3-p.bal:9
```
This contains a line number in the original `bal` file relevant to the error instruction.
Actual output is,
```
panic: divide by zero
```
In the error object in Javascript. It has two properties. The message and the stack.
The stack contains details where the exception was thrown.  But it is a line in the WASM file. The line of the error output is missing in the actual output.

**Comment by poorna2152** [comment]
- Range of ints representable in `WASM`
-9223372036854775808 - 9223372036854775807

- Range of ints representable based on the test cases
-9223372036854775807 - 9223372036854775807

When outside this range it is expected to throw an Error.
In but in `WASM` it does not throw an error for this.(Behaves in a circular way: 9223372036854775807 + 1 = -9223372036854775808). 
Therefore should the handling of this Exception be done on the WAT code.
```
if op1 > 0 && op2 > 0 && result < 0 
  throw "overflow"
```

**Comment by manuranga** [comment]
1) Debug line info options:
a) Differ this for a later subset.
b) "Bake-in" the lines as part of error creation
c) Use https://yurydelendik.github.io/webassembly-dwarf/
Lets go with a) for now

2) Wrapping 
https://github.com/WebAssembly/design/blob/main/FutureFeatures.md#integer-overflow-detection
I think we'll have to do a per-check, but your proposed per-check is wrong. Please take a look at https://www.cs.utah.edu/~regehr/papers/overflow12.pdf

**Comment by manuranga** [comment]
btw ballerina ints can have the value -9223372036854775808

**Comment by poorna2152** [comment]
Following checks for overflow,
- For addition:
```
if (s1 > 0) && (s2 > 0) 
  if (s1 > (INT_MAX − s2))
    throw overflow
else if (s1 < 0) && (s2 < 0)  
  if s1 < (INT_MIN − s2)
    throw overflow
```
- For substraction:
```
if (s1 > 0) && (s2 < 0)  
  if s1 > (INT_MAX + s2)
    throw overflow
else if (s1 < 0) && (s2 > 0)
  if s1 < (INT_MIN + s2)
    throw overflow
```
- For multiplication:
```
if ((s1 > 0 && s2 > 0)
  if (s2 > INT_MAX/s1))
    throw overflow
else
  if abs(s2) > abs(INT_MIN/s1)
    throw overflow
```
- For division:
```
if (s1 == INT_MIN) && (s2 == -1)
  throw overflow
```

**Comment by poorna2152** [comment]
Possible methods,
- Creating a seperate WASM Module for checking overflow and importing the functions from that module to do the checks and throw errors.
e.g.: [main.wat](https://gist.github.com/poorna2152/9b5a1252a4a3f39eeac0159895376b10), [overflow.wat](https://gist.github.com/poorna2152/f2fd71ff7d8a68cb793ac893b943dc06), [runtime.js](https://gist.github.com/poorna2152/058ef8baf95c5c65ee8a7d01b4a89ac2)
- Defining overflow checking functions and importing them to the module.
e.g.: [main.wat](https://gist.github.com/poorna2152/9b5a1252a4a3f39eeac0159895376b10), [runtime.js](https://gist.github.com/poorna2152/7199d51f69e6220a82e88cfdde9cf680)

**Comment by poorna2152** [comment]
- Using inline checks for handling overflows
