### ISSUE TITLE
Create initial `wasm.print` module

### ISSUE THREAD

**Issue by manuranga** [poorna2152/nballerina#2]
Create a new `wasm.print` similar to `llvm.print`.
Let's come up initial API that is enough to create `printBoolean` function.
Please post the planed public API here before implementing (Maybe start with a sample unit test).

**Comment by poorna2152** [comment]
https://github.com/poorna2152/nballerina/pull/4

**Comment by poorna2152** [comment]
https://github.com/poorna2152/nballerina/pull/7

**Comment by poorna2152** [comment]
Initial Module function implementation:  https://github.com/poorna2152/nballerina/pull/8
