### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by poorna2152** [poorna2152/nballerina#48]

**Comment by poorna2152** [comment]
The code for checking overflows is currently added inline. For example checking overflows in addition,
```
    (if 
      (i32.and 
        (i64.gt_s 
          (local.get $0) 
          (i64.const 0)) 
        (i64.gt_s 
          (local.get $1) 
          (i64.const 0))) 
      (if 
        (i64.gt_s 
          (local.get $0) 
          (i64.sub 
            (i64.const 9223372036854775807) 
            (local.get $1))) 
        (throw $overflow)) 
      (if 
        (i32.and 
          (i64.lt_s 
            (local.get $0) 
            (i64.const 0)) 
          (i64.lt_s 
            (local.get $1) 
            (i64.const 0))) 
        (if 
          (i64.lt_s 
            (local.get $0) 
            (i64.sub 
              (i64.const -9223372036854775808) 
              (local.get $1))) 
          (throw $overflow))))
```

This is currently generated by a using functions in the `print.wasm `module with a code which looks ugly https://github.com/poorna2152/nballerina/blob/wback_subset07/compiler/modules/wback/number.bal#L80-L140. 

Is it okay to create a runtime wat function rather than doing it inline. When implementing subset 02 we discussed to have it inline. I am guessing that is as an optimization. But if I create a function then the `wasm-opt` tool is going to inline it anyway. That would be more work to the optimizer but the code would be clean. Shall I  make it inline

**Comment by manuranga** [comment]
If it's getting inlined later, function sounds like a good idea to me.
